### ISSUE TITLE
Splunk Add On: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by cfloriani** [tenchi-security/zanshin-splunk-add-on#9]
Hi goys

I'm having a problem running the collection with the addon, it's complaining about the SSL certificate validation, I analyzed the script and I couldn't find where to disable this check

`09-26-2022 11:48:51.865 -0300 ERROR ExecProcessor [61687 ExecProcessor] - message from "/splunk/bin/python3.7 /splunk/etc/apps/TA-zanshin-add-on-for-splunk/bin/zanshin_following_alerts.py" ERROR[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1106)`

**Comment by asieira** [comment]
> Hi goys
> 
> I'm having a problem running the collection with the addon, it's complaining about the SSL certificate validation, I analyzed the script and I couldn't find where to disable this check
> 
> `09-26-2022 11:48:51.865 -0300 ERROR ExecProcessor [61687 ExecProcessor] - message from "/splunk/bin/python3.7 /splunk/etc/apps/TA-zanshin-add-on-for-splunk/bin/zanshin_following_alerts.py" ERROR[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1106)`

Can you tell me which version of Splunk and of our Splunk Add-On you are running so we can better try to reproduce the problem?

**Comment by asieira** [comment]
@cfloriani I have an updated version of the add-on that will probably fix the issues you are having. Can you please contact our customer support team to get it and let me know if it fixes things?

**Comment by asieira** [comment]
Please try using this updated version and let support @ tenchisecurity.com know if you are still having issues: https://github.com/tenchi-security/zanshin-splunk-add-on/releases/tag/v1.0.1-1

**Comment by cfloriani** [comment]
tks guys

**Comment by asieira** [comment]
> tks guys

Can you please let us know if this solved the problem?
